//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11
{
    using System;
    using System.Collections.Generic;
    
    public partial class protbl
    {
        public int ProId { get; set; }
        public string ProName { get; set; }
        public string ProImg { get; set; }
        public string ProDes { get; set; }
    }
}
